geekshop/adminapp/urls.py
from django.urls import path
from adminapp.views import (IndexTemplateView,

                            UserListView,
                            UserCreateView,
                            UserUpdateView,
                            UserDeleteView,

                            ProductsListView,
                            ProductCreateView,
                            ProductUpdateView,
                            ProductDeleteView)
from adminapp.views import (CategoryReadView, create_category, CategoryUpdateView, CategoryDeleteView)

app_name = 'adminapp'
urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),

    path('users/', UserListView.as_view(), name='admin_users'),
    path('user-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('user-delete/<int:pk>/', UserDeleteView.as_view(), name='admin_users_delete'),
    path('user-update/<int:pk>/', UserUpdateView.as_view(), name='admin_users_update'),

    path('products/', ProductsListView.as_view(), name='admin_products'),
    path('product-create/', ProductCreateView.as_view(), name='create_product'),
    path('product-delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('product-update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),

    path('categories/', CategoryReadView.as_view(), name='admin_categories'),
    path('category-create/', create_category, name='create_category'),
    path('category-delete/<int:id>/', CategoryDeleteView.as_view(), name='delete_category'),
    path('category-update/<int:id>/', CategoryUpdateView.as_view(), name='update_category')]

geekshop/authapp/urls.py
from django.urls import path

from authapp.views import Logout, ProfileFormView, Login, RegisterFormView

app_name = 'authapp'
urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('register/', RegisterFormView.as_view(), name='register'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('logout/', Logout.as_view(), name='logout'),
    path('verify/<str:email>/<str:activate_key>/', RegisterFormView.verify, name='verify')
]

geekshop/basket/urls.py
from django.urls import path

from basket.views import basket_add, basket_remove, basket_edit

app_name = 'basket'
urlpatterns = [
    path('add/<int:id>/', basket_add, name='basket_add'),
    path('remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('edit/<int:basket_id>/<int:quantity>/', basket_edit, name='basket_edit')

]

geekshop/geekshop/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp.views import MainPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPageView.as_view(), name='index'),
    # path('', MainPageView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('admins/', include('adminapp.urls', namespace='admins')),
    path('order/', include('orderapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [path('debug/', include(debug_toolbar.urls))]

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.core.exceptions import ValidationError

from authapp.models import User
from mainapp.models import Product, ProductCategories
from authapp.validator import validate_name, validate_email


class AdminRegisterForm(UserCreationForm):
    email = forms.CharField(widget=forms.TextInput(),
                            validators=[validate_email])

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'last_name', 'first_name', 'email', 'image', 'age')

    def __init__(self, *args, **kwargs):
        super(AdminRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['password1'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['password2'].widget.attrs['placeholder'] = 'Повторите пароль'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Введите фамилию'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Введите имя'
        self.fields['email'].widget.attrs['placeholder'] = 'Введите email'
        self.fields['image'].widget.attrs['placeholder'] = 'Добавьте фотографию'
        self.fields['age'].widget.attrs['placeholder'] = 'Возраст'

        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'


class AdminProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'last_name', 'first_name', 'email', 'image', 'age')

    def __init__(self, *args, **kwargs):
        super(AdminProfileForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = True

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control py-4'

        self.fields['image'].widget.attrs['class'] = 'custom-file-input'


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'category', 'quantity', 'price')

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control py-4'


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'category', 'quantity', 'descriptions', 'image', 'price')

    def __init__(self, *args, **kwargs):
        super(ProductCreateForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Введите название продукта'
        self.fields['category'].widget.attrs['placeholder'] = 'Введите название категории'
        self.fields['quantity'].widget.attrs['placeholder'] = 'Введите количество'
        self.fields['price'].widget.attrs['placeholder'] = 'Введите стоимость'
        self.fields['descriptions'].widget.attrs['placeholder'] = 'Введите описание продукта'
        self.fields['image'].widget.attrs['placeholder'] = 'Добавьте фотографию'

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'


class ProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'category', 'quantity', 'descriptions', 'image', 'price')

    def __init__(self, *args, **kwargs):
        super(ProductUpdateForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Введите название продукта'
        self.fields['category'].widget.attrs['placeholder'] = 'Введите название категории'
        self.fields['quantity'].widget.attrs['placeholder'] = 'Введите количество'
        self.fields['price'].widget.attrs['placeholder'] = 'Введите стоимость'
        self.fields['descriptions'].widget.attrs['placeholder'] = 'Введите описание продукта'
        self.fields['image'].widget.attrs['placeholder'] = 'Добавьте фотографию'

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'


class CategoryUpdateForm(forms.ModelForm):
    discount = forms.IntegerField(widget=forms.NumberInput(), label='скидка', required=False, min_value=0, max_value=90,
                                  initial=0)

    class Meta:
        model = ProductCategories
        fields = ('name', 'descriptions', 'discount')

    def __init__(self, *args, **kwargs):
        super(CategoryUpdateForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Введите название категории'
        self.fields['descriptions'].widget.attrs['placeholder'] = 'Введите описание категории'

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control py-4'


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = ProductCategories
        fields = ('name', 'descriptions',)

    def __init__(self, *args, **kwargs):
        super(CategoryCreateForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Введите название категории'
        self.fields['descriptions'].widget.attrs['placeholder'] = 'Введите описание категории'

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control py-4'

geekshop/adminapp/views.py
from typing import Any
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.db import connection
from django.db.models import F
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.http import HttpRequest, HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, TemplateView, CreateView
from adminapp.forms import (AdminRegisterForm,
                            AdminProfileForm,
                            ProductCreateForm,
                            ProductUpdateForm,
                            CategoryUpdateForm,
                            CategoryCreateForm)
from adminapp.mixins import BaseClassContextMixin, CustomDispatchMixin
from mainapp.models import Product, ProductCategories
from authapp.models import User


# Create your views here.


class IndexTemplateView(TemplateView, BaseClassContextMixin, CustomDispatchMixin):
    template_name = 'adminapp/admin.html'  # отдаём шаблон
    title = 'Main page'  # меняем title в контексте


class UserListView(ListView, BaseClassContextMixin, CustomDispatchMixin):
    model = User
    template_name = 'adminapp/admin-users-read.html'
    title = 'Administration | Users'
    # меняем object_list на users в контексте шаблонизатора
    context_object_name = 'users'


class UserCreateView(CreateView, BaseClassContextMixin, CustomDispatchMixin):
    model = User
    template_name = 'adminapp/admin-user-create.html'
    form_class = AdminRegisterForm  # обязательно указать форму!
    title = 'Administration | Create User'
    success_url = reverse_lazy('adminapp:admin_users')


class UserUpdateView(UpdateView, BaseClassContextMixin, CustomDispatchMixin):
    model = User
    template_name = 'adminapp/admin-user-update-delete.html'
    form_class = AdminProfileForm
    title = 'Administration | Edit Users'
    success_url = reverse_lazy('adminapp:admin_users')


class UserDeleteView(DeleteView, CustomDispatchMixin):
    model = User
    template_name = 'adminapp/admin-user-update-delete.html'
    form_class = AdminProfileForm
    success_url = reverse_lazy('adminapp:admin_users')

    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.object = self.get_object()  # == User.objects.get(id=id)
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class ProductsListView(ListView, BaseClassContextMixin, CustomDispatchMixin):
    model = Product
    template_name = 'adminapp/admin-products-read.html'
    title = 'Administration | Products'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.all().select_related()


class ProductDeleteView(DeleteView, CustomDispatchMixin):
    model = Product
    template_name = 'adminapp/admin-product-update-delete.html'
    form_class = ProductUpdateForm
    success_url = reverse_lazy('adminapp:admin_products')


class ProductCreateView(CreateView, BaseClassContextMixin, CustomDispatchMixin):
    model = Product
    template_name = 'adminapp/admin-product-create.html'
    form_class = ProductCreateForm
    title = 'Administration | Create Product'
    success_url = reverse_lazy('adminapp:admin_products')


class ProductUpdateView(UpdateView, BaseClassContextMixin, CustomDispatchMixin):
    model = Product
    template_name = 'adminapp/admin-product-update-delete.html'
    form_class = ProductUpdateForm
    title = 'Administration | Edit Product'
    success_url = reverse_lazy('adminapp:admin_users')


class CategoryReadView(ListView, BaseClassContextMixin):
    model = ProductCategories
    template_name = 'adminapp/admin-category-read.html'
    title = 'Administration | Categories'
    context_object_name = 'categories'


@user_passes_test(lambda u: u.is_superuser)
def create_category(request):
    if request.method == 'POST':
        form = CategoryCreateForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.set_level(request, messages.SUCCESS)
            messages.success(request, 'Категория успешно создалась!')
        else:
            print(form.errors)
    else:
        form = CategoryCreateForm()
    context = {
        'title': 'Administration | Create Category',
        'form': form
    }
    return render(request, 'adminapp/admin-category-create.html', context)


class CategoryUpdateView(UpdateView, CustomDispatchMixin):
    model = ProductCategories
    template_name = 'adminapp/admin-category-update-delete.html'
    success_url = reverse_lazy('admins:admin_category')
    form_class = CategoryUpdateForm

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                print(f'Скидка {discount} % к товарам категории {self.object.name}')
                self.object.product_set.update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.queries)
        return HttpResponseRedirect(self.get_success_url())


class CategoryDeleteView(DeleteView, CustomDispatchMixin):
    model = ProductCategories
    template_name = 'adminapp/admin-category-update-delete.html'
    success_url = reverse_lazy('admins:admin_category')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.product_set.update(is_active=False)
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


# signals
@receiver(pre_save, sender=ProductCategories)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)
        db_profile_by_type(sender, 'UPDATE', connection.queries)

geekshop/adminapp/templates/adminapp/admin-category-create.html
{% extends 'adminapp/base.html' %}
{% block context %}
    <div class="container-fluid">
        <h1 class="mt-4">{{ title | title }}</h1>
        <form action="{% url 'adminapp:create_category' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.name.id_for_label }}">Название категории</label>
                        {{form.name}}
                    </div>
                </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.descriptions.id_for_label }}">Описание</label>
                    {{ form.descriptions }}
                </div>
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/admin-category-read.html
{% extends 'adminapp/base.html' %}
{% block context %}
    <div class="container-fluid">
        <h1 class="mt-4">{{ title | title }}</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категории
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя категории</th>
                            <th>Описание</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя категории</th>
                            <th>Описание</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for category in categories %}
                            <tr>
                                <td><a href="{% url 'adminapp:update_category' category.id %}"
                                       style="color: dodgerblue">{{ category.name }}</a></td> {# Ссылка на обновление данных категории #}
                                <td>{{ category.descriptions }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:create_category' %}">
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/admin-category-update-delete.html
{% extends 'adminapp/base.html' %}
{% block context %}
    <div class="container-fluid">
        <h1 class="mt-4">{{ title | title }} | {{ current_category.name }}</h1>
        <div class="card-body">
            <form action="{% url 'adminapp:update_category' current_category.id %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.name.id_for_label }}">Название категории</label>
                            {{ form.name }}
                        </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.descriptions.id_for_label }}">Описание</label>
                        {{ form.descriptions }}
                    </div>
                </div>
                {% comment %} <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.descriptions.id_for_label }}">Товары категории</label>
                        {{ form.descriptions }}
                    </div>
                </div> {% endcomment %}
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
            <form action="{% url 'adminapp:delete_category' current_category.id %}">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/admin-product-read.html
{% extends 'adminapp/base.html' %}
{% block context %}
    <div class="container-fluid">
        <h1 class="mt-4">Товары</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Товары
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Название товара</th>
                            <th>Категория</th>
                            <th>Цена</th>
                            <th>Количество</th>
                            <th>Описание</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Название товара</th>
                            <th>Категория</th>
                            <th>Цена</th>
                            <th>Количество</th>
                            <th>Описание</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for product in products %}
                            <tr>
                                <td><a href="{% url 'adminapp:update_product' product.id %}"
                                       style="color: dodgerblue">{{ product.name }}</a></td> {# Ссылка на обновление данных товара #}
                                <td>{{ product.category }}</td>
                                <td>{{ product.price }}</td>
                                <td>{{ product.quantity }}</td>
                                <td>{{ product.descriptions }}</td>
                                <td class="text-center">
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:create_product' %}">
                    <button class="btn btn-success">Создать товар</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/admin-product-update-delete.html
{% extends 'adminapp/base.html' %}
{% block context %}
    <div class="container-fluid">
        <h1 class="mt-4">{{ title | title }} | {{ product.name }}</h1>
        <div class="card-body">
            <form action="{% url 'adminapp:update_product' pk=product.id %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.name.id_for_label }}">Название товара</label>
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена</label>
                            {{ form.price }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                изображение</label>
                            {{ form.image }}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.descriptions.id_for_label }}">Описание</label>
                        {{ form.descriptions }}
                    </div>
                    <div class="col-lg-4">
                        <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество</label>
                        {{ form.quantity }}
                    </div>
                    <div class="col-lg-2">
                        <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                        {{ form.category }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
            <form action="{% url 'adminapp:delete_product' pk=product.id %}">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/admin-products-read.html
{% extends 'adminapp/base.html' %}
{% block context %}
    <div class="container-fluid">
        <h1 class="mt-4">{{ title | title }}</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Товары
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Название товара</th>
                            <th>Категория</th>
                            <th>Цена</th>
                            <th>Количество</th>
                            <th>Описание</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Название товара</th>
                            <th>Категория</th>
                            <th>Цена</th>
                            <th>Количество</th>
                            <th>Описание</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for product in products %}
                            <tr>
                                <td><a href="{% url 'adminapp:update_product' pk=product.id %}"
                                       style="color: dodgerblue">{{ product.name }}</a></td> {# Ссылка на обновление данных товара #}
                                <td>{{ product.category }}</td>
                                <td>{{ product.price }}</td>
                                <td>{{ product.quantity }}</td>
                                <td>{{ product.descriptions }}</td>
                                <td class="text-center">
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:create_product' %}">
                    <button class="btn btn-success">Создать товар</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/admin-user-update-delete.html
{% extends 'adminapp/base.html' %}
{% block context %}
    <div class="container-fluid">
        <h1 class="mt-4">{{ title | title }} | {{ user.username }}</h1>
        <div class="card-body">
            <form action="{% url 'adminapp:admin_users_update' user.id %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{ form.image }}
                            <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-4">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                    <div class="col-lg-2">
                        <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                        {{ form.age }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
            <form action="{% url 'adminapp:admin_users_delete' pk=user.id %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/admin.html
{% extends 'adminapp/base.html' %}
{% block context %}
    <div class="container-fluid">
        <h1 class="mt-4">Административная панель</h1>
    </div>
{% endblock %}