geekshop/authapp/urls.py
from django.urls import path

from authapp.views import Logout, ProfileFormView, Login, RegisterFormView

app_name = 'authapp'
urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('register/', RegisterFormView.as_view(), name='register'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('logout/', Logout.as_view(), name='logout'),
    path('verify/<str:email>/<str:activate_key>/', RegisterFormView.verify, name='verify')
]

geekshop/basket/urls.py
from django.urls import path

from basket.views import basket_add, basket_remove, basket_edit

app_name = 'basket'
urlpatterns = [
    path('add/<int:id>/', basket_add, name='basket_add'),
    path('remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('edit/<int:basket_id>/<int:quantity>/', basket_edit, name='basket_edit')

]

geekshop/geekshop/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp.views import MainPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPageView.as_view(), name='index'),
    # path('', MainPageView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('admins/', include('adminapp.urls', namespace='admins')),
    path('order/', include('orderapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [path('debug/', include(debug_toolbar.urls))]

geekshop/authapp/models.py
from datetime import timedelta

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.
from django.utils.timezone import now


class User(AbstractUser):
    image = models.ImageField(upload_to='users_image', blank=True)
    age = models.PositiveIntegerField(default=18)

    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(auto_now=True, blank=True, null=True)

    def is_activation_key_expired(self) -> bool:
        if now() <= self.activation_key_expires + timedelta(hours=48):
            return False
        return True


class UserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'W'

    GENDER_CHOICES = (
        (MALE, 'М'),
        (FEMALE, 'Ж'),
    )

    user = models.OneToOneField(User, unique=True, null=True, db_index=True, on_delete=models.CASCADE)
    about = models.TextField(verbose_name='О себе', blank=True, null=False)
    gender = models.CharField(verbose_name='Пол', choices=GENDER_CHOICES, blank=True, max_length=2)
    langs = models.CharField(verbose_name='Язык', blank=True, max_length=5, default='RU')

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, created, **kwargs):
        if not created:
            instance.userprofile.save()

geekshop/authapp/forms.py
import hashlib
import random
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django import forms
from django.core.exceptions import ValidationError

from authapp.models import User
from authapp.validator import validate_name, validate_email
from authapp.models import UserProfile


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(), validators=[validate_name])

    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['password'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['username'].required = True
        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'


class UserRegisterForm(UserCreationForm):
    email = forms.CharField(widget=forms.TextInput(),
                            validators=[validate_email])

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'last_name', 'first_name', 'email')

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['password1'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['password2'].widget.attrs['placeholder'] = 'Повторите пароль'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Введите фамилию'
        # Делаем поле обязательным к заполнению
        self.fields['last_name'].required = True
        self.fields['first_name'].widget.attrs['placeholder'] = 'Введите имя'
        self.fields['email'].widget.attrs['placeholder'] = 'Введите email'

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control py-4'

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save()
        user.is_active = False
        salt = hashlib.sha1(
            str(random.random()).encode('utf-8')).hexdigest()[:6]
        user.activation_key = hashlib.sha1(
            (user.email + salt).encode('utf-8')).hexdigest()
        user.save()
        return user


class UserProfileForm(UserChangeForm):
    image = forms.ImageField(widget=forms.FileInput(), required=False)
    age = forms.IntegerField(widget=forms.NumberInput(), required=False)

    class Meta:
        model = User
        fields = ('username', 'last_name', 'first_name', 'email', 'image', 'age')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['readonly'] = True

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control py-4'

        self.fields['image'].widget.attrs['class'] = 'custom-file-input'


class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(UserProfileUpdateForm, self).__init__(*args, **kwargs)
        for filed_name, field in self.fields.items():
            if filed_name != 'gender' and filed_name != 'langs':
                field.widget.attrs['class'] = 'form-control py-4'
            else:
                field.widget.attrs['class'] = 'form-control'

geekshop/authapp/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.contrib import auth, messages
from django.contrib.auth.views import LoginView, LogoutView, FormView
from django.views.generic import UpdateView
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import UpdateView

# Create your views here.

from authapp.forms import UserLoginForm, UserRegisterForm, UserProfileForm, UserProfileUpdateForm
from adminapp.mixins import BaseClassContextMixin, UserDispatchMixin
from authapp.models import User
from basket.models import Basket


class Login(LoginView, BaseClassContextMixin):
    form_class = UserLoginForm
    title = 'GeekShop | Авторизация'
    template_name = 'authapp/login.html'


class RegisterFormView(FormView, BaseClassContextMixin):
    model = User
    title = 'GeekShop | Registration'
    form_class = UserRegisterForm
    template_name = 'authapp/register.html'
    success_url = reverse_lazy('authapp:login')

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            user = form.save()
            if self.send_verify_link(user):
                messages.set_level(request, messages.SUCCESS)
                messages.success(request, 'Вы успешно зарегистрировались')
                return HttpResponseRedirect(reverse('authapp:login'))
            else:
                messages.set_level(request, messages.ERROR)
                messages.error(request, form.errors)
        else:
            messages.set_level(request, messages.ERROR)
            messages.error(request, form.errors)
        context = {'form': form}
        return render(request, self.template_name, context)

    @staticmethod
    def send_verify_link(user):
        verify_link = reverse('authapp:verify', args=[user.email, user.activation_key])
        subject = f'Для активации учетной записи {user.username} пройдите по ссылке'
        message = f'Для подтверждения учетной записи {user.username} на портале \n {settings.DOMAIN_NAME}{verify_link}'
        return send_mail(subject, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)

    def verify(self, email, activate_key):
        try:
            user = User.objects.get(email=email)
            if user and (user.activation_key == activate_key and not user.is_activation_key_expired()):
                user.activation_key = ''
                user.activation_key_expires = None
                user.is_active = True
                user.save()
                auth.login(
                    self, user, backend='django.contrib.auth.backends.ModelBackend')
            return render(self.request, 'authapp/verification.html')
        except NameError:
            return HttpResponseRedirect(reverse('index'))


class ProfileFormView(UpdateView, BaseClassContextMixin, UserDispatchMixin):
    model = User
    template_name = 'authapp/profile.html'
    form_class = UserProfileForm
    success_url = reverse_lazy('authapp:profile')
    title = 'GeekShop | Profile'

    def post(self, request, *args, **kwargs):
        form = UserProfileForm(data=request.POST, files=request.FILES, instance=request.user)
        profile_form = UserProfileUpdateForm(
            data=request.POST, files=request.FILES, instance=request.user.userprofile)
        if form.is_valid() and profile_form.is_valid():
            form.save()
        return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super(ProfileFormView, self).get_context_data()
        context['profile'] = UserProfileUpdateForm(instance=self.request.user.userprofile)
        return context

    def form_valid(self, form):
        messages.set_level(self.request, messages.SUCCESS)
        messages.success(self.request, 'Вы успешно сохранили профиль')
        super().form_valid(form)
        return HttpResponseRedirect(self.get_success_url())

    def get_object(self, queryset=None):
        return User.objects.get(id=self.request.user.pk)


class Logout(LogoutView):
    template_name = 'mainapp/index.html'

geekshop/authapp/templates/authapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                  {% block content %}
                  {% endblock %}
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
</body>
</html>

geekshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% block content %}
    <div class="col-lg-5">
        {% if form.non_field_errors  or messages %}

            <div class="alert {% if messages %} alert-success{% else %}alert-warning{% endif %} alert-dismissible fade show"
                 role="alert"
                 style="margin-top: 50px;">

                {% if messages %}
                    {% for massage in messages %}
                        {{ massage }}
                    {% endfor %}
                {% else %}
                    {% for error in form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
            </div>
            <div class="card-body">
                <form action="{% url 'authapp:login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                        {{ form.password }}
                    </div>
                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                        <a class="small" href="#">Забыли пароль?</a>
                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small"><a href="{% url 'authapp:register' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                <div class="list-group-horizontal card-footer text-center small">
                    <a href="{% url 'social:begin' 'vk-oauth2' %}?next=/">
                        <i class="fab fa-vk"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/authapp/templates/authapp/profile.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block css %}

    <link href="  {% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <h4 class="mt-3 mb-3">Профиль</h4>
                <div class="col-lg-12 text-center">
                    <img width="100" height="100"
                         src='{% if user.image %}
                             {{ user.image.url }}{% else %}{% static 'vendor/img/users/default_avatar.jpg' %} {% endif %}'
                         class="img-thumbnail">
                </div>
                <form action="{% url 'authapp:profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                    изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-4">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-4">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>

                        <div class="col-lg-4">
                            <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                            {{ form.age }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-row">
                                <div class="col-lg-6">
                                    <label class="small mb-1" for="{{ profile.gender.id_for_label }}">Пол</label>
                                    {{ profile.gender }}
                                </div>
                                <div class="col-lg-6">
                                    <label class="small mb-1" for="{{ profile.langs.id_for_label }}">Язык</label>
                                    {{ profile.langs }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ profile.about.id_for_label }}">О нас</label>
                            {{ profile.about }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-5">
                {% include 'basket/basket.html' %}
            </div>
        </div>
    </div>

{% endblock %}

geekshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}

{% block content %}
    <div class="col-lg-7">
        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                 style="margin-top: 50px;">
                {% for error in form.errors %}
                    {{ error | escape }}
                {% endfor %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
            </div>
            <div class="card-body">
                <form action="{% url 'authapp:register' %}" method="post">
                    {% csrf_token %}

                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                                {{ form.password1 }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                    пароля</label>
                                {{ form.password2 }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group mt-4 mb-0">
                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small"><a href="{% url 'authapp:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/authapp/templates/authapp/verification.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <div class="col-lg-5">
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header"><h3 class="text-center font-weight-light my-4">Активация профиля</h3>
            </div>
            <div class="card-body text-center">
                {% if user.is_authenticated %}
                    <h3>Поздравляем!</h3>
                    <br>
                    <h4>Пользователь {{ user.username }} подтвержден.</h4>
                {% else %}
                    <h3>Верификация не пройдена.</h3>
                {% endif %}
                <br>
                <button class="btn btn-round form-control">
                    <a href="{% url 'index' %}" class="">на главную</a>
                </button>
            </div>
        </div>
    </div>
{% endblock %}