geekshop/adminapp/urls.py
from django.urls import path
from adminapp.views import (IndexTemplateView,

                            UserListView,
                            UserCreateView,
                            UserUpdateView,
                            UserDeleteView,

                            ProductsListView,
                            ProductCreateView,
                            ProductUpdateView,
                            ProductDeleteView)
from adminapp.views import (CategoryReadView, create_category, CategoryUpdateView, CategoryDeleteView)

app_name = 'adminapp'
urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),

    path('users/', UserListView.as_view(), name='admin_users'),
    path('user-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('user-delete/<int:pk>/', UserDeleteView.as_view(), name='admin_users_delete'),
    path('user-update/<int:pk>/', UserUpdateView.as_view(), name='admin_users_update'),

    path('products/', ProductsListView.as_view(), name='admin_products'),
    path('product-create/', ProductCreateView.as_view(), name='create_product'),
    path('product-delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('product-update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),

    path('categories/', CategoryReadView.as_view(), name='admin_categories'),
    path('category-create/', create_category, name='create_category'),
    path('category-delete/<int:id>/', CategoryDeleteView.as_view(), name='delete_category'),
    path('category-update/<int:id>/', CategoryUpdateView.as_view(), name='update_category')]

geekshop/authapp/urls.py
from django.urls import path

from authapp.views import Logout, ProfileFormView, Login, RegisterFormView

app_name = 'authapp'
urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('register/', RegisterFormView.as_view(), name='register'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('logout/', Logout.as_view(), name='logout'),
    path('verify/<str:email>/<str:activate_key>/', RegisterFormView.verify, name='verify')
]

geekshop/basket/urls.py
from django.urls import path

from basket.views import basket_add, basket_remove, basket_edit

app_name = 'basket'
urlpatterns = [
    path('add/<int:id>/', basket_add, name='basket_add'),
    path('remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('edit/<int:basket_id>/<int:quantity>/', basket_edit, name='basket_edit')

]

geekshop/geekshop/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp.views import MainPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPageView.as_view(), name='index'),
    # path('', MainPageView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('admins/', include('adminapp.urls', namespace='admins')),
    path('order/', include('orderapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [path('debug/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page

from mainapp.views import ProductDetail, products

app_name = 'mainapp'
urlpatterns = [
    path('', products, name='products'),
    path('detail/<int:pk>/', ProductDetail.as_view(), name='detail'),
    path('category/<int:id_category>/', products, name='category'),
    path('page/<int:page>/', products, name='page'),
    path('orders/', include('orderapp.urls', namespace='orders'))
]

geekshop/orderapp/urls.py
from django.urls import path
from orderapp.views import (OrderListView,
                            OrderCreateView,
                            OrderUpdateView,
                            OrderReadView,
                            OrderDeleteView,
                            order_forming_complete,
                            get_product_price)

app_name = 'orderapp'
urlpatterns = [
    path('', OrderListView.as_view(), name='list'),
    path('create/', OrderCreateView.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', OrderDeleteView.as_view(), name='delete'),
    path('read/<int:pk>/', OrderReadView.as_view(), name='read'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='order_forming_complete'),
    path('product/<int:pk>/price/', get_product_price, name='product_price'),

]

geekshop/mainapp/models.py
""" models for product and category"""

from django.db import models


class ProductCategories(models.Model):
    name = models.CharField(max_length=64)
    descriptions = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=128)
    image = models.ImageField(upload_to='product_images', blank=True)
    descriptions = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategories, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} | {self.category}'

    @staticmethod
    def get_items():
        return Product.objects.all()

geekshop/mainapp/views.py
import os
import json

from django.conf import settings
from django.core.cache import cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView

from mainapp.models import Product, ProductCategories

MODULE_DIR = os.path.dirname(__file__)


def read_file(name):
    file_path = os.path.join(MODULE_DIR, name)
    return json.load(open(file_path, encoding='utf-8'))


def get_link_category():
    if settings.LOW_CACHE:
        key = 'link_category'
        link_category = cache.get(key)
        if link_category is None:
            link_category = ProductCategories.objects.all()
            cache.set(key, link_category)
        return link_category
    else:
        return ProductCategories.objects.all()


def get_product_from_category(category, page):
    product = Product.objects.filter(category_id=category).select_related(
        'category') if category else Product.objects.all().select_related('category')
    if settings.LOW_CACHE:
        key = f'link_product{category}{page}' if category else 'link_product'
        link_product = cache.get(key)
        if link_product is None:
            link_product = product
            cache.set(key, link_product)
        return link_product
    else:
        return product


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product{pk}'
        product = cache.get(key)
        if product is None:
            product = Product.objects.get(pk=pk)
            cache.set(key, product)
        return product
    else:
        return Product.objects.get(pk=pk)


def products(request, id_category=None, page=1):
    if id_category:
        products_ = Product.objects.filter(category_id=id_category).select_related()
    else:
        products_ = get_product_from_category(None, None)

    pagination = Paginator(products_, per_page=6)

    try:
        product_pagination = pagination.page(page)
    except PageNotAnInteger:
        product_pagination = pagination.page(1)
    except EmptyPage:
        product_pagination = pagination.page(pagination.num_pages)

    content = {
        'title': 'Geekshop - Каталог',
        'categories': ProductCategories.objects.all(),
        # 'categories': get_link_category(),
        'products': product_pagination

    }

    return render(request, 'mainapp/products.html', content)


class MainPageView(TemplateView):
    title = 'GeekShop'
    template_name = 'mainapp/index.html'


# class ProductsView(TemplateView, BaseClassContextMixin):
#     title = 'GeekShop | Catalog'
#     template_name = 'mainapp/products.html'
#
#     def get_context_data(self, id_category=None, page=1):
#         products_ = Product.objects.filter(
#             category_id=id_category).select_related() if id_category else Product.objects.all().select_related(
#             'category')  # указать по какому полю вытаскивать записи из БД
#
#         pagination = Paginator(products_, per_page=3)
#         try:
#             product_pagination = pagination.page(page)
#         except PageNotAnInteger:
#             product_pagination = pagination.page(1)
#         except EmptyPage:
#             product_pagination = pagination.page(pagination.num_pages)
#
#         context = {'categories': ProductCategories.objects.all(),
#                    'products': product_pagination}
#         return context


class ProductDetail(DetailView):
    model = Product
    template_name = 'mainapp/detail.html'

    def get_context_data(self, **kwargs):
        context = super(ProductDetail, self).get_context_data()
        context['product'] = get_product(self.kwargs.get('pk'))
        return context

geekshop/mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %}
    {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainapp:products' %}">Каталог <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:login' %}">Войти <i
                                class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item">

                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle" href="" data-toggle="dropdown">
                                {{ user.username | default:'User' }}
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark" href="{% url 'authapp:profile' %}">
                                        Profile
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" href="{% url 'orders:list' %}">
                                        Orders
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    {% if user.is_staff or user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'adminapp:index' %}">
                                <i class="fas fa-users-cog"></i>
                            </a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}


{% block footer %}

{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'js/orders_scripts.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

geekshop/mainapp/templates/mainapp/detail.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    <a href="{% url 'mainapp:products' %}" class="list-group-item">Все</a>
                </div>
            </div>

            <div class="col-lg-9">
                <div class="row my-5">
                    <div class="card" style="width: 20rem;">
                        <img src="/media/{{ product.image }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ product.price }} руб</li>
                            <li class="list-group-item">В наличии: {{ product.quantity }}</li>
                        </ul>
                    </div>
                </div>

            </div>

        </div>
    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2022</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
        <link href="{% static 'css/index.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">GeekShop Store</h1>
                    <p>
                        Новые образы и лучшие бренды на GeekShop Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'mainapp:products' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a href="{% url 'mainapp:category' category.id %}"
                           class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                </div>
            </div>
            <div class="col-lg-9">
                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                {% include 'mainapp/includes/card.html' %}

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if products.has_previous %} {% url 'mainapp:page' products.previous_page_number %} {% endif %}"
                               tabindex="-1" aria-disabled="true">Previous</a>
                        </li>

                        {% for page in products.paginator.page_range %}

                            <li class="page-item"><a class="page-link"
                                                     href="{% url 'mainapp:page' page %}">{{ page }}</a></li>

                        {% endfor %}
                        <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if products.has_next %} {% url 'mainapp:page' products.next_page_number %} {% endif %}"
                               tabindex="-1" aria-disabled="true">Next</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>

{% endblock %}

{% block footer %}

    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2022</p>
        </div>
    </footer>
{% endblock %}